name: Test
on:
  push:
  pull_request:
    branches:
      - main
      - develop
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run pylint
        run: |
          python -m pylint --rcfile=./.pylintrc ./**/*.py
      - name: Test with pytest
        run: |
          python -m pytest
        env:
          MIN_EFFECTIF: 10
